#!/usr/bin/env python3


import argparse
import logging
import os
import sys
import difflib

# Custom imports
import pdb_tofasta


# Global variables
NAME = "subunit.py"
logger = None

# Known subunits
SUBUNITS = {
	# Tca
	"SEHETRLVANLLENYNKVIRPVEHHTHFVDITVGLQLIQLISVDEVNQIVETNVRLRQQWIDVRLRWNPADYGGIKKIRLPSDDVWLPDLVLYNNADGDFAIVHMTKLLLDYTGKIMWTPPAIFKSYCEIIVTHFPFDQQNCTMKLGIWTYDGTKVSISPESDRPDLSTFMESGEWVMKDYRGWKHWVYYTCCPDTPYLDITYHFIMQRIPLYFVVNVIIPCLLFSFLTGLVFYLPTDSGEKMTLSISVLLSLTVFLLVIVELIPSTSSAVPLIGKYMLFTMIFVISSIIITVVVINTHHRSPSTHTMPQWVRKIFIDTIPNVMFFSTMKRASKEKQENKIFADDIDISDISGKQVTGEVIFQTPLIKNPDVKSAIEGVKYIAEHMKSDEESSNAAEEWKYVAMVIDHILLCVFMLICIIGTVSVFAGRLIELSQEG": "a",
	"SVMEDTLLSVLFETYNPKVRPAQTVGDKVTVRVGLTLTNLLILNEKIEEMTTNVFLNLAWTDYRLQWDPAAYEGIKDLRIPSSDVWQPDIVLMNNNDGSFEITLHVNVLVQHTGAVSWQPSAIYRSSCTIKVMYFPFDWQNCTMVFKSYTYDTSEVTLQHALDAKGEREVKEIVINKDAFTENGQWSIEHKPSRKNWRSDDPSYEDVTFYLIIQRKPLFYIVYTIIPCILISILAILVFYLPPDAGEKMSLSISALLAVTVFLLLLADKVPETSLSVPIIIRYLMFIMILVAFSVILSVVVLNLHHRSPNTHTMPNWIRQIFIETLPPFLWIQRPVTTPSPDSKPTIISRANDEYFIRKPAGDFVCPVDNARVAVQPERLFSEMKWHLNGLTQPVTLPQDLKEAVEAIKYIAEQLESASEFDDLKKDWQYVAMVADRLFLYVFFVICSIGTFSIFLDASHNVPPDNPFA": "b",
	"VNEEERLINDLLIVNKYNKHVRPVKHNNEVVNIALSLTLSNLISLKETDETLTSNVWMDHAWYDHRLTWNASEYSDISILRLPPELVWIPDIVLQNNNDGQYHVAYFCNVLVRPNGYVTWLPPAIFRSSCPINVLYFPFDWQNCSLKFTALNYDANEITMDLMTDTIDGKDYPIEWIIIDPEAFTENGEWEIIHKPAKKNIYPDKFPNGTNYQDVTFYLIIRRKPLFYVINFITPCVLISFLASLAFYLPAESGEKMSTAISVLLAQAVFLLLTSQRLPETALAVPLIGKYLMFIMSLVTGVIVNCGIVLNFHFRTPSTHVLSTRVKQIFLEKLPRILHMSRADESEQPDWQNDLKLRRSSSVGYISKAQEYFNIKSRSELMFEKQSERHGLVPRVTPRIGFGNNNENIAASDQLHDEIKSGIDSTNYIVKQIKEKNAYDEEVGNWNLVGQTIDRLSMFIITPVMVLGTIFIFVMGNFNHPPAKPFEGDPFDYSSDHPRCA": "d",
	"NEEGRLIEKLLGDYDKRIIPAKTLDHIIDVTLKLTLTNLISLNEKEEALTTNVWIEIQWNDYRLSWNTSEYEGIDLVRIPSELLWLPDVVLENNVDGQFEVAYYANVLVYNDGSMYWLPPAIYRSTCPIAVTYFPFDWQNCSLVFRSQTYNAHEVNLQLSAEEGEAVEWIHIDPEDFTENGEWTIRHRPAKKNYNWQLTKDDTDFQEIIFFLIIQRKPLFYIINIIAPCVLISSLVVLVYFLPAQAGGQKCTLSISVLLAQTIFLFLIAQKVPETSLNVPLIGKYLIFVMFVSMLIVMNCVIVLNVSLRTPNTHSLSEKIKHLFLGFLPKYLGMQLEPSEETPEKPQPRRRSSFGIMIKAEEYILKKPRSELMFEEQKDRHGLKRVNKMTSDIDIGTTVDLYKDLANFAPEIKSCVEACNFIAKSTKEQNDSGSENENWVLIGKVIDKACFWIALLLFSIGTLAIFLTGHFNQVPEFPFPGDPRKYVP": "g",
	# Lsa
	"FSSVCANPDAKRLYDDLLSNYDRLIRPVGNSSDRLTVKMGLKLSQIIGIDMKRQIMITNVWVAQEWHDYKLKWKPEDYGGVKHLHVPSQNIWLPDIVLYNNADGNYEVTIMTKAVLHFSGRVVWNPPAIYKSSCEIDVEFFPFDEQKCFMKFGSWTYDGYMVDLRHINQKGSSSEIEIGMDLQEYYISTEWDVMTAPAVRNEKYYPCCEEPYPDIIFYLTLRRKSLFYTVNVIIPCVGISFLSVLVFYLPSDSGEKVSLSISILLSLTVFFLLLAEIIPSTSIAVPLLGKYLLFTMILVTFSVMLTIGVLNVNFRTPATHKMAPWVRKTFVEFLPRFLFIRRPEKEEEEEEEVLFTPETECDEKSQALLQSSQPPMFLQKEDLLKIPPPFSLDHDEKSLQRISPSRDDIQSKISPSSGDPFYGSGNSGFPLYPLPLGGIDSSKDSVSELVPTFYGGSESMGYHGDYSSCERHLDKAHELNPALEKAMNALKFVAQHVKNEDNFESFSDDWKYVAMVLDRILLWVFTVACVFGTAGIIMAAPSHQDTRQPIDIQFSKVDKISALRMMPESLKSQR": "a1",
	"NGNPDAKRLYDDLLSNYNRLIRPVSNHTEKVTVKLGLRLSQLVDLNLKDQILTTNVWLEHEWKDYKFTWDPSEYGGVTEIYVPSEHIWLPDIILYNNADGDYIVTTMTKAILHYDGKVVWTPPAIFKSSCEIDVEFFPFDKQTCFLKFGSWSFDGFQVDLVHINSQPDNDTVSYGMDLSEYYLNVEWDILEVPAERHVKTYPCCPEPYPDIYFSIIIRRKPLFYVVNLIIPCVGIFYLSILVFYLPAQSGEKTALVIAILVSQTLYFTLVIEVIPATSKTLPLLGRYLIFSMIFIAIAVTLTTIILNLHYRKPSTHRMPQWVRRTFIQRLPRILLMRVPIQVIKDTMKTRRSKYLRQSDPALKSLAGKYGEDDDEEDDAKGNGGLNSQLRGHLNGLYRGLTKIMTSTCDVMDVKSSTSPFAIEKAVHNIMFIKHHMKRQDEFDAEDQDWGIVAMVLDRLFLWVFGISALVGSIMILVESPNMYEEVSPIDVIFSKIALEESSRVSQEKVFM": "a2",
	"RLFSPGHGSQEEERLVRDLFRGYNKLIRPVQNMTQKVEVAFGLAFIQLINVNEKNQIMKSNVWLRFVWNDYQLQWDEADYGGISVLRLPPDKVWKPDIVLFNNADGNYEVRYKSNVLIYPDGEVLWVPPAIYQSSCTIDVTYFPFDQQTCIMKFGSWTFTGDQVSLTLYNNKDYVDLSDYWKSGTWDIIEVPAYLNIHNDTLPTETDISFYITIRRKTLFYTVNLILPTVLISFLCVLVFYLPAEAGEKVTLGISILLSLVVFLLLVSKILPPTSLVLPLIAKYLLFTFIMNTVSILVTVVIINWNFRGPRTHSMPNWIRVLFLKYLPIVLFMRRPKKTRLRWMMEMPGQSRRIPPPHPSYCPPPTNNGTSSSSNNNNNTSNNNHQHHPHPDSSSSPLSGGIKLTAPNAPLPPPPPVSPPSSDLIKNKIEIMELNDMQNTNSSQPQPPNSSSHIHHPTCKLNQSHQGSFDDEEVEDEDDDLTTSPTGRGNHHHPPPPHHHQHLHHHHHHHLDEEEDQAQQHPPPPHHRGGRRNSDEDDGSEAFLSPEAYRATQAVEFIAEHLRNEDEYLQIREDWKFVAMVVDRMQLYVFFIVTTVGTVGILMDAPHIFEYVDQDKIIDIYKGK": "b1",
	"GNPHAKRLYDDLLSNYNRLIRPVSNNTEKLTVRLGLKLSQLIDVDLKNQVMTTNVWVEQKWLDYKLNWKPEEYGGVEMLYVPSQHIWLPDIVLFNNADGKYEVTLMTKARLKYTGEVVWKPPAIYKSSCKINVEWFPFDEQSCDMKFGSWTYDGFQVDLKHVDQEKGSNVVKVGIDLKEFYYSVEWDILEVPATRNEEYYTNDRGEEDDYQGKLLTDITFMMTLRRKTLFYTVNLIIPCVGISFLTVLVFYLPSDSGEKVTLCISILLSLTVFFLLLAEIIPPTSLAVPLLGKYLLFTMILVTLSICVTVGVLNIHFRSPATHRMSPWMRKIFIHIMPRMLLMTRPHYIPRYSAEPPLKSRSNDDLMYNQDQDSKKLNGHCGPTTNEDQCKKNGKDEQDSTKPNKKKSISNVACALRGVEFIAQHIKNADKDNEVIEDWKFIAMVMDRLFLWLFTIACIMGTGGIILRAPSLYDMRDPIDAKLSEIPKF": "b2",
}


def parse_commandline_options():
	# Define argument parser
	parser = argparse.ArgumentParser(description="Identify subunit from PDB file")
	parser.add_argument("file", help="PDB-file to operate on.")
	parser.add_argument(
		"-c", "--chain", default="A", help="Chain to identify (Default: %(default)s)"
	)
	parser.add_argument(
		"-v",
		"--verbose",
		action="count",
		default=0,
		help="Increase verbosity (prints more information), can be invoked multiple times",
	)

	# Parse arguments
	args = parser.parse_args()

	# Detect invalid input
	if len(args.chain) > 1 or not args.chain.isalpha():
		logger.error(
			"Malform chain selection. You must select a single chain to identify."
		)
		sys.exit(1)
	args.chain = args.chain.upper()

	return args


def init_logger():
	global logger

	# Define logger
	logger = logging.getLogger(NAME)

	# Configure handler
	stderr_handler = logging.StreamHandler(sys.stderr)
	stderr_handler.setLevel(logging.WARNING)
	stderr_handler.setFormatter(logging.Formatter(fmt="%(levelname)s: %(message)s"))

	# Attach handler to logger
	logger.addHandler(stderr_handler)


def configure_logger(args):
	# Map verbosity to logging levels
	level_map = {
		0: logging.WARNING,
		1: logging.INFO,
		2: logging.DEBUG,
	}

	# Configure logger
	logger.setLevel(level_map[args.verbose])

	# Configure handler
	stdout_handler = logging.StreamHandler(sys.stdout)
	stdout_handler.addFilter(MaxLevelFilter(logging.INFO))
	stdout_handler.setFormatter(logging.Formatter(fmt="%(message)s"))

	# Attach handler to logger
	logger.addHandler(stdout_handler)


class MaxLevelFilter(logging.Filter):
	"""
	A custom filter to ensure messages above a spesified level do not pass
	through to the handler
	"""

	def __init__(self, max_level):
		super().__init__()
		self.max_level = max_level

	def filter(self, record):
		return record.levelno <= self.max_level


def main():
	# Setup
	init_logger()
	args = parse_commandline_options()
	configure_logger(args)
	if not os.path.isfile(args.file):
		logger.error(f"PDB-file '{args.file}' does not exist or is not a file")
		sys.exit(1)

	# Using pdb-tools' pdb_tofasta, map chains to fasta sequences
	chains = {}
	with open(args.file, 'rt') as fp:
		fastagen = pdb_tofasta.run(fp, "multi")
		chain_id = None
		for chain in fastagen:
			if chain[0:1] == ">":
				chain_id = chain.strip()[-1]
			else:
				lines = chain.splitlines()
				chains[chain_id] = "".join(map(lambda x: x.strip(), lines))

	# Check if requested chain exists
	if args.chain not in chains:
		logger.error(f"Requested chain {args.chain} not found in file")

	# Match FASTA to subunit
	matches = difflib.get_close_matches(chains[args.chain], SUBUNITS.keys())
	if len(matches) == 0:
		logger.error(f"Unknown subunit '{chains[args.chain]}'")
		sys.exit(1)
	else:
		print(SUBUNITS[matches[0]])


# Run main function
if __name__ == "__main__":
	main()
